# Generated by Django 4.1.7 on 2023-03-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yougetapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioquality',
            name='audio_quality',
            field=models.CharField(max_length=5),
        ),
    ]
